### ISSUE TITLE
簡単な利用規約を掲載する

### ISSUE THREAD

**Issue by udcxx** [udcxx/recitone#3]
## Why

利用上のルールが定められていないため

## What

利用規約/注意事項を掲載し、ルールを明確化する

## ToDo

- [x] 利用規約の制定
- [x] ページ上への掲載
- [x] テストアップ
- [x] Pull request作成、README更新
- [x] 本番公開

## Version

v1.1.2（仮）

**Comment by udcxx** [comment]
草案

* 入力いただいた内容、および、ご利用環境のグローバルIPアドレスは、利用状況の把握や、今後のアップデートの参考のために収集いたします。
* 収集したデータは、API 実行などの理由で、第三者へ提供することがあります。
* 収集したデータに、個人情報に該当する情報が含まれていることを管理者が確認した場合や、利用者から依頼があった場合には、該当のデータを削除いたします。
* 本ツールは OpenAI 社の OpenAI API を利用しています。OpenAI 社のプライバシーポリシーは <a href="https://openai.com/ja/policies/privacy-policy" target="_blank">こちら</a> をご確認ください。
* 必要以上に処理を実行することや、プログラムなどによって自動的に処理を実行すること、サーバーに負荷を与える行為、二次使用、リバースエンジニアリング、その他法律に反する行為や運営の妨げとなる行為は禁止します。
* 出力される結果や、その結果を用いたことによって発生する如何なる事象にも責任は負いません。利用者の責任によって利用するものとします。

**Comment by udcxx** [comment]
### CSS
```css
.rules {
    width: 100%;
    margin: 40px auto;
    padding: 15px 60px 15px 30px;
    color: #333;
    border-radius: 10px;
    box-sizing: border-box;
    background-color: #d1d5d5;
}
.rules--title {
    font-size: 18px; font-weight: bold;
    cursor: pointer;
}
.rules--item {
    margin-bottom: 0.7em;
    font-size: 14px;
    line-height: 1.2em;
}
```

### HTML
```html
<details class="rules">
    <summary class="rules--title">注意事項</summary>
    <ul class="rules--list">
        <li class="rules--item">入力いただいた内容、および、ご利用環境のグローバルIPアドレスは、利用状況の把握や、今後のアップデートの参考のために収集いたします。</li>
        <li class="rules--item">収集したデータは、API 実行などの理由で、第三者へ提供することがあります。</li>
        <li class="rules--item">収集したデータに、個人情報に該当する情報が含まれていた場合や、利用者から依頼があった場合には、確認が取れ次第、即刻削除いたします。</li>
        <li class="rules--item">本ツールは OpenAI 社の OpenAI API を利用しています。OpenAI 社のプライバシーポリシーは <a href="https://openai.com/ja/policies/privacy-policy" target="_blank">こちら</a> をご確認ください。</li>
        <li class="rules--item">必要以上に処理を実行することや、プログラムなどによって自動的に処理を実行すること、サーバーに負荷を与える行為、二次使用、リバースエンジニアリング、その他法律に反する行為や運営の妨げとなる行為は禁止します。</li>
        <li class="rules--item">出力される結果や、その結果を用いたことによって発生する如何なる事象にも責任は負いません。利用者の責任によって利用するものとします。</li>
    </ul>
</details>
```
